NAME_CLIENT=client
NAME_SERVER=server
NAME_CLIENT_BONUS=client_bonus
NAME_SERVER_BONUS=server_bonus

CC = gcc
CFLAGS = -Wall -Werror -Wextra

CLIENT_SRC=client.c tools.c
SERVER_SRC=server.c tools.c
CLIENT_BONUS_SRC=client_bonus.c tools_bonus.c
SERVER_BONUS_SRC=server_bonus.c tools_bonus.c

CLIENT_OBJ=$(CLIENT_SRC:.c=.o)
SERVER_OBJ=$(SERVER_SRC:.c=.o)
CLIENT_BONUS_OBJ=$(CLIENT_BONUS_SRC:.c=.o)
SERVER_BONUS_OBJ=$(SERVER_BONUS_SRC:.c=.o)

all: $(NAME_SERVER) $(NAME_CLIENT)
	@echo "DONE !"
$(NAME_SERVER): $(SERVER_OBJ)
	$(CC) $(CFLAGS) $(SERVER_OBJ) -o $(NAME_SERVER)
$(NAME_CLIENT): $(CLIENT_OBJ)
	$(CC) $(CFLAGS) $(CLIENT_OBJ) -o $(NAME_CLIENT)

clean:
	rm -f *.o

fclean: clean
	rm -f $(NAME_SERVER) $(NAME_CLIENT)
	rm -f $(NAME_CLIENT_BONUS) $(NAME_SERVER_BONUS)

re:	fclean all $(NAME_CLIENT_BONUS) $(NAME_SERVER_BONUS)

bonus: $(NAME_CLIENT_BONUS) $(NAME_SERVER_BONUS)


$(NAME_CLIENT_BONUS): $(CLIENT_BONUS_OBJ)
	$(CC) $(CFLAGS) $(CLIENT_BONUS_OBJ) -o $(NAME_CLIENT_BONUS)
$(NAME_SERVER_BONUS): $(SERVER_BONUS_OBJ)
	$(CC) $(CFLAGS) $(SERVER_BONUS_OBJ) -o $(NAME_SERVER_BONUS)

.PHONY: clean fclean re all bonus
